# Generated by Django 6.0.5 on 2026-08-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
