# Generated by Django 6.0.5 on 2026-08-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_profile_old_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='old_card',
            new_name='old_cart',
        ),
    ]
